# -*- coding: utf-8 -*-
"""project2_classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VU24f873IwVErtVvByHXhVF9psN6Dsx_
"""

# ============================================
# DecodeLabs Project 2: Data Classification Using AI
# Dataset: Wine (sklearn built-in)
# Algorithm: K-Nearest Neighbors (KNN)
# ============================================

# Step 1: Libraries import karo
import pandas as pd
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Step 2: Dataset load karo
data = load_wine()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target

# Step 3: Dataset samjho
print("Dataset shape:", data.data.shape)
print("Classes:", data.target_names)
print("\nFirst 5 rows:")
print(df.head())
print("\nClass distribution:")
print(df['target'].value_counts())

# Step 4: Data ko training (80%) aur testing (20%) mein split karo
X_train, X_test, y_train, y_test = train_test_split(
    data.data, data.target, test_size=0.2, random_state=42)
print("\nTraining samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

# Step 5: Feature scaling (KNN distance-based hai, isliye zaroori)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Step 6: Model train karo (KNN, k=3)
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)

# Step 7: Test data pe prediction karo
y_pred = model.predict(X_test)

# Step 8: Model ko evaluate karo
print("\nAccuracy:", round(accuracy_score(y_test, y_pred) * 100, 2), "%")
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=data.target_names))

## Results and Analysis

- Accuracy: 94.44% (34 out of 36 test samples classified correctly)
- Confusion Matrix: class_0 and class_2 were predicted perfectly. Only 2 samples of class_1 were misclassified (1 as class_0, 1 as class_2).
- Precision, recall and F1-score are between 0.86 and 1.00 for all classes, so the model performs consistently.
- Conclusion: KNN with feature scaling works well on the Wine dataset. Accuracy can be improved further by tuning k or using cross-validation.